env:
  AWS_ACCOUNT_ALIAS: common
  ENVIRONMENT_NAME: common
  DEPLOY_ENVIRONMENT_NAME: production
  S3_PATH: dd
  S3_HOSTNAME: demos.developer.virtru.com
  USE_NODE_10: true

agents:
  queue: "${BUILDKITE_QUEUE:-default}"
agent_queue: &agent_queue "queue=${BUILDKITE_QUEUE:-default}"

steps:

  - label: ":npm: Install Dependencies (CI)"
    command: "buildkite-scripts/mars/wrap/npm-ci.sh"
    agents:
      - *agent_queue

  - wait

  - label: ":npm: :lock: NPM Audit"
    command: ".buildkite/scripts/npm-audit.sh"
    agents:
      - *agent_queue

  - wait

  - label: ":upside_down_face: Run linter"
    command: "buildkite-scripts/scripts/run-linting.sh"
    agents:
      - *agent_queue

  - wait

  - label: "Create build artifact"
    command: "tar -cvzf build.tar.gz --xform 's/simple/build/' simple"
    artifact_paths:
      - "build.tar.gz"
    agents:
      - *agent_queue

  - wait

  - label: "Upload dd demo to s3"
    command: "buildkite-scripts/scripts/developer-demos/deploy-to-s3.sh"
    agents:
      - *agent_queue

  - wait
  - label: ':npm: NPM Build (Production)'
    command: 'buildkite-scripts/scripts/npm-build.sh'
    branches: 'master'
    env:
      NODE_ENV: 'production'
    agents:
      - *agent_queue

  - label: ':npm: NPM Build (Staging)'
    command: 'buildkite-scripts/scripts/npm-build.sh'
    branches: 'develop'
    env:
      NODE_ENV: 'staging'
    agents:
      - *agent_queue

  - label: ':npm: NPM Build (Develop)'
    command: 'buildkite-scripts/scripts/npm-build.sh'
    branches: '!master !develop'
    env:
      NODE_ENV: 'develop'
    agents:
      - *agent_queue

  - wait
  # Build and Deploy (Staging)
  - label: ':s3: Deploy to S3 Staging'
    command: 'buildkite-scripts/scripts/developer-demos/deploy-to-s3.sh'
    branches: 'develop'
    env:
      S3_PATH: 'dd-staging'
    agents:
      - *agent_queue
  - wait

  - label: ':s3: Deploy to S3 Production'
  command: 'buildkite-scripts/scripts/developer-demos/deploy-to-s3.sh'
  branches: 'master'
  env:
    S3_PATH: 'dd-production'
  agents:
    - *agent_queue
  - wait

  - label: ':s3: Invalidate CloudFront Cache Staging'
    command: 'buildkite-scripts/scripts/developer-demos/invalidate-cloudfront-cache.sh'
    branches: 'develop'
    env:
      S3_PATH: 'dd-staging'
    agents:
      - *agent_queue

  - label: ':s3: Invalidate CloudFront Cache Production'
    command: 'buildkite-scripts/scripts/developer-demos/invalidate-cloudfront-cache.sh'
    branches: 'master'
    env:
      S3_PATH: 'dd-production'
    agents:
      - *agent_queue

  - block: 'Unblock Deploy'

  - block: 'Check your branch name'
    prompt: 'Your branch name does not match expected options. This will not result in a successful deployment unless you have explicitly defined environment variables.'
    branches: '!master !develop !*release/* !*feature/* !*hotfix/* !*bug/*'

  # Build and Deploy (Develop)
  - label: ':s3: Deploy to S3 Develop'
    command: 'buildkite-scripts/scripts/developer-demos/deploy-to-s3.sh'
    branches: '!master !develop'
    env:
      S3_PATH: 'dd-develop'
    agents:
      - *agent_queue
  - label: ":s3: Invalidate CloudFront Cache"
    command: "buildkite-scripts/scripts/developer-demos/invalidate-cloudfront-cache.sh"
    agents:
      - *agent_queue
